create extension if not exists pgcrypto;

create table if not exists public.asc_coach_salaries(id uuid primary key default gen_random_uuid(),legacy_id text unique,coach_id text,period text,amount numeric,status text,paid_at timestamptz,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_competition_registrations(id uuid primary key default gen_random_uuid(),legacy_id text unique,athlete_id text,competition_id text,status text,amount numeric,submitted_at timestamptz,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_weekly_targets(id uuid primary key default gen_random_uuid(),legacy_id text unique,athlete_id text,status text,title text,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_skill_journals(id uuid primary key default gen_random_uuid(),legacy_id text unique,athlete_id text,coach_name text,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_dryland_tasks(id uuid primary key default gen_random_uuid(),legacy_id text unique,athlete_id text,title text,task_date timestamptz,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_reschedule_requests(id uuid primary key default gen_random_uuid(),legacy_id text unique,athlete_id text,status text,preferred_date date,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_athlete_packages(id uuid primary key default gen_random_uuid(),legacy_id text unique,athlete_id text,title text,status text,expiry_date date,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_parent_reminders(id uuid primary key default gen_random_uuid(),legacy_id text unique,athlete_id text,enabled boolean not null default false,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_coach_notifications(id uuid primary key default gen_random_uuid(),legacy_id text unique,recipient_role text,recipient_id text,athlete_id text,coach_id text,title text,message text,type text,reference_type text,reference_id text,deep_link text,read_at timestamptz,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_audit_trail(id uuid primary key default gen_random_uuid(),legacy_id text unique,reference_id text,category text,title text,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);
create table if not exists public.asc_version_history(id uuid primary key default gen_random_uuid(),legacy_id text unique,reference_id text,title text,data jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now(),deleted_at timestamptz);

create or replace function public.asc_legacy_array(collection_name text)
returns table(legacy_id text,data jsonb) language sql stable as $$
 with sources as(
  select 1 priority,payload from public.class_app_data_backup where class_id='aqilah-swimming-club'
  union all select 2,payload from public.class_app_data where class_id='aqilah-swimming-club'
 ), candidates as(
  select priority,x value,nullif(x->>'id','') item_id,payload from sources cross join lateral jsonb_array_elements(case when jsonb_typeof(payload->collection_name)='array' then payload->collection_name else '[]'::jsonb end)x
 ), tombstones as(
  select k from sources cross join lateral jsonb_object_keys(case when jsonb_typeof(payload->'__tombstones'->collection_name)='object' then payload->'__tombstones'->collection_name else '{}'::jsonb end)k
 ), ranked as(select item_id,value,row_number()over(partition by item_id order by priority)rn from candidates where item_id is not null and not exists(select 1 from tombstones where k=item_id))
 select item_id,value from ranked where rn=1
$$;

insert into public.asc_coach_salaries(legacy_id,coach_id,period,amount,status,paid_at,data,created_at,updated_at)
select legacy_id,data->>'coachId',data->>'period',case when data->>'amount'~'^\d+(\.\d+)?$' then(data->>'amount')::numeric end,data->>'status',case when data->>'paidAt'~'^\d{4}-\d{2}-\d{2}T' then(data->>'paidAt')::timestamptz end,data,coalesce(nullif(data->>'createdAt','')::timestamptz,now()),coalesce(nullif(data->>'updatedAt','')::timestamptz,now()) from public.asc_legacy_array('coachSalaries') on conflict(legacy_id)do nothing;
insert into public.asc_competition_registrations(legacy_id,athlete_id,competition_id,status,amount,submitted_at,data,created_at,updated_at)
select legacy_id,data->>'athleteId',data->>'competitionId',data->>'status',case when data->>'amount'~'^\d+(\.\d+)?$' then(data->>'amount')::numeric end,case when data->>'submittedAt'~'^\d{4}-\d{2}-\d{2}T' then(data->>'submittedAt')::timestamptz end,data,coalesce(nullif(data->>'submittedAt','')::timestamptz,now()),coalesce(nullif(data->>'updatedAt','')::timestamptz,now()) from public.asc_legacy_array('competitionRegistrations') on conflict(legacy_id)do nothing;
insert into public.asc_weekly_targets(legacy_id,athlete_id,status,title,data,updated_at)select legacy_id,data->>'athleteId',data->>'status',data->>'mission',data,coalesce(nullif(data->>'updatedAt','')::timestamptz,now())from public.asc_legacy_array('weeklyTargets')on conflict(legacy_id)do nothing;
insert into public.asc_skill_journals(legacy_id,athlete_id,coach_name,data,updated_at)select legacy_id,data->>'athleteId',data->>'coachName',data,coalesce(nullif(data->>'updatedAt','')::timestamptz,now())from public.asc_legacy_array('skillJournals')on conflict(legacy_id)do nothing;
insert into public.asc_dryland_tasks(legacy_id,athlete_id,title,task_date,data,created_at)select legacy_id,data->>'athleteId',data->>'title',case when data->>'date'~'^\d{4}-\d{2}-\d{2}T' then(data->>'date')::timestamptz end,data,coalesce(nullif(data->>'date','')::timestamptz,now())from public.asc_legacy_array('drylandTasks')on conflict(legacy_id)do nothing;
insert into public.asc_reschedule_requests(legacy_id,athlete_id,status,preferred_date,data,created_at)select legacy_id,data->>'athleteId',data->>'status',case when data->>'preferredDate'~'^\d{4}-\d{2}-\d{2}$' then(data->>'preferredDate')::date end,data,coalesce(nullif(data->>'createdAt','')::timestamptz,now())from public.asc_legacy_array('rescheduleRequests')on conflict(legacy_id)do nothing;
insert into public.asc_athlete_packages(legacy_id,athlete_id,title,status,expiry_date,data,updated_at)select legacy_id,data->>'athleteId',data->>'packageName',case when coalesce(nullif(data->>'remainingSessions','')::numeric,0)>0 then'active'else'completed'end,case when data->>'expiryDate'~'^\d{4}-\d{2}-\d{2}$'then(data->>'expiryDate')::date end,data,coalesce(nullif(data->>'updatedAt','')::timestamptz,now())from public.asc_legacy_array('athletePackages')on conflict(legacy_id)do nothing;
insert into public.asc_coach_notifications(legacy_id,recipient_role,recipient_id,coach_id,title,message,type,reference_type,reference_id,deep_link,read_at,data,created_at)
select legacy_id,'coach',coalesce(data->>'recipientId',data->>'coachId'),coalesce(data->>'coachId',data->>'recipientId'),data->>'title',data->>'message',coalesce(data->>'type','coach_notification'),data->>'referenceType',data->>'referenceId',coalesce(data->>'deepLink',data->>'page'),case when coalesce((data->>'read')::boolean,false)then coalesce(nullif(data->>'readAt','')::timestamptz,now())end,data,coalesce(nullif(data->>'createdAt','')::timestamptz,now())from public.asc_legacy_array('coachNotifications')on conflict(legacy_id)do nothing;
insert into public.asc_audit_trail(legacy_id,reference_id,category,title,data,created_at)select legacy_id,data->>'recordId',data->>'collection',data->>'action',data,coalesce(nullif(data->>'at','')::timestamptz,now())from public.asc_legacy_array('auditTrail')on conflict(legacy_id)do nothing;
insert into public.asc_version_history(legacy_id,reference_id,title,data,created_at)select legacy_id,data->>'revision',data->>'reason',data,coalesce(nullif(data->>'at','')::timestamptz,now())from public.asc_legacy_array('versionHistory')on conflict(legacy_id)do nothing;

with sources as(select 1 priority,payload from public.class_app_data_backup where class_id='aqilah-swimming-club' union all select 2,payload from public.class_app_data where class_id='aqilah-swimming-club'),entries as(select priority,e.key athlete_id,e.value enabled,row_number()over(partition by e.key order by priority)rn from sources cross join lateral jsonb_each(case when jsonb_typeof(payload->'parentReminders')='object'then payload->'parentReminders'else'{}'::jsonb end)e),tombstones as(select k from sources cross join lateral jsonb_object_keys(case when jsonb_typeof(payload->'__tombstones'->'parentReminders')='object'then payload->'__tombstones'->'parentReminders'else'{}'::jsonb end)k)
insert into public.asc_parent_reminders(legacy_id,athlete_id,enabled,data)select'REM-'||athlete_id,athlete_id,case when jsonb_typeof(enabled)='boolean'then enabled::text::boolean else false end,jsonb_build_object('id','REM-'||athlete_id,'athleteId',athlete_id,'enabled',enabled)from entries where rn=1 and not exists(select 1 from tombstones where k=athlete_id or k='REM-'||athlete_id)on conflict(legacy_id)do nothing;

do $$declare t text;begin foreach t in array array['asc_coach_salaries','asc_competition_registrations','asc_weekly_targets','asc_skill_journals','asc_dryland_tasks','asc_reschedule_requests','asc_athlete_packages','asc_parent_reminders','asc_coach_notifications','asc_audit_trail','asc_version_history']loop
 execute format('create index if not exists %I on public.%I(legacy_id) where deleted_at is null',t||'_active_legacy_idx',t);
 execute format('alter table public.%I enable row level security',t);
 execute format('grant select,insert,update,delete on public.%I to anon,authenticated',t);
 if not exists(select 1 from pg_policies where schemaname='public'and tablename=t and policyname=t||'_select')then execute format('create policy %I on public.%I for select to anon,authenticated using(true)',t||'_select',t);end if;
 if not exists(select 1 from pg_policies where schemaname='public'and tablename=t and policyname=t||'_insert')then execute format('create policy %I on public.%I for insert to anon,authenticated with check(true)',t||'_insert',t);end if;
 if not exists(select 1 from pg_policies where schemaname='public'and tablename=t and policyname=t||'_update')then execute format('create policy %I on public.%I for update to anon,authenticated using(true)with check(true)',t||'_update',t);end if;
 if not exists(select 1 from pg_policies where schemaname='public'and tablename=t and policyname=t||'_delete')then execute format('create policy %I on public.%I for delete to anon,authenticated using(true)',t||'_delete',t);end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename=t)then execute format('alter publication supabase_realtime add table public.%I',t);end if;
 end loop;end$$;
