create table if not exists public.asc_announcements (legacy_id text primary key, title text, content text, published_at timestamptz, data jsonb not null default '{}'::jsonb, deleted_at timestamptz, updated_at timestamptz not null default now());
alter table public.asc_announcements enable row level security;
do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_announcements' and policyname='ASC announcements read') then create policy "ASC announcements read" on public.asc_announcements for select to anon,authenticated using(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_announcements' and policyname='ASC announcements insert') then create policy "ASC announcements insert" on public.asc_announcements for insert to anon,authenticated with check(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_announcements' and policyname='ASC announcements update') then create policy "ASC announcements update" on public.asc_announcements for update to anon,authenticated using(true) with check(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_announcements' and policyname='ASC announcements delete') then create policy "ASC announcements delete" on public.asc_announcements for delete to anon,authenticated using(true); end if;
end $$;
do $$ declare p jsonb; begin if to_regclass('public.class_app_data_backup') is not null then execute 'select payload from public.class_app_data_backup where class_id=$1 and jsonb_array_length(coalesce(payload->''announcements'',''[]''::jsonb))>0 limit 1' into p using 'aqilah-swimming-club'; end if; if p is null then select payload into p from public.class_app_data where class_id='aqilah-swimming-club' and jsonb_array_length(coalesce(payload->'announcements','[]'::jsonb))>0 limit 1; end if; insert into public.asc_announcements(legacy_id,title,content,published_at,data,deleted_at,updated_at) select x->>'id',coalesce(nullif(x->>'title',''),'Pengumuman'),coalesce(nullif(x->>'body',''),nullif(x->>'content','')),case when x->>'date' ~ '^\d{4}-\d{2}-\d{2}$' then ((x->>'date')||'T00:00:00Z')::timestamptz else now() end,x,null,now() from jsonb_array_elements(coalesce(p->'announcements','[]'::jsonb)) x where nullif(x->>'id','') is not null on conflict(legacy_id) do nothing; end $$;
