create table if not exists public.asc_schedules (legacy_id text primary key, data jsonb not null default '{}'::jsonb, deleted_at timestamptz, updated_at timestamptz not null default now());
alter table public.asc_schedules enable row level security;
grant select,insert,update,delete on public.asc_schedules to anon,authenticated;
do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_schedules' and policyname='ASC schedules read') then create policy "ASC schedules read" on public.asc_schedules for select to anon,authenticated using(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_schedules' and policyname='ASC schedules insert') then create policy "ASC schedules insert" on public.asc_schedules for insert to anon,authenticated with check(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_schedules' and policyname='ASC schedules update') then create policy "ASC schedules update" on public.asc_schedules for update to anon,authenticated using(true) with check(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_schedules' and policyname='ASC schedules delete') then create policy "ASC schedules delete" on public.asc_schedules for delete to anon,authenticated using(true); end if;
end $$;
do $$ declare p jsonb; begin if to_regclass('public.class_app_data_backup') is not null then execute 'select payload from public.class_app_data_backup where class_id=$1 and jsonb_array_length(coalesce(payload->''schedules'',''[]''::jsonb))>0 limit 1' into p using 'aqilah-swimming-club'; end if; if p is null then select payload into p from public.class_app_data where class_id='aqilah-swimming-club' and jsonb_array_length(coalesce(payload->'schedules','[]'::jsonb))>0 limit 1; end if; insert into public.asc_schedules(legacy_id,data,deleted_at,updated_at) select x->>'id',x,null,now() from jsonb_array_elements(coalesce(p->'schedules','[]'::jsonb)) x where nullif(x->>'id','') is not null on conflict(legacy_id) do nothing; end $$;
