create table if not exists public.asc_registrations (legacy_id text primary key, data jsonb not null default '{}'::jsonb, deleted_at timestamptz, updated_at timestamptz not null default now());
alter table public.asc_registrations enable row level security;
grant select,insert,update,delete on public.asc_registrations to anon,authenticated;
do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_registrations' and policyname='ASC registrations read') then create policy "ASC registrations read" on public.asc_registrations for select to anon,authenticated using(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_registrations' and policyname='ASC registrations insert') then create policy "ASC registrations insert" on public.asc_registrations for insert to anon,authenticated with check(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_registrations' and policyname='ASC registrations update') then create policy "ASC registrations update" on public.asc_registrations for update to anon,authenticated using(true) with check(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='asc_registrations' and policyname='ASC registrations delete') then create policy "ASC registrations delete" on public.asc_registrations for delete to anon,authenticated using(true); end if;
end $$;
do $$ declare p jsonb; begin if to_regclass('public.class_app_data_backup') is not null then execute 'select payload from public.class_app_data_backup where class_id=$1 and jsonb_array_length(coalesce(payload->''pendingRegistrations'',''[]''::jsonb))>0 limit 1' into p using 'aqilah-swimming-club'; end if; if p is null then select payload into p from public.class_app_data where class_id='aqilah-swimming-club' and jsonb_array_length(coalesce(payload->'pendingRegistrations','[]'::jsonb))>0 limit 1; end if; insert into public.asc_registrations(legacy_id,data,deleted_at,updated_at) select x->>'id',x,null,now() from jsonb_array_elements(coalesce(p->'pendingRegistrations','[]'::jsonb)) x where nullif(x->>'id','') is not null on conflict(legacy_id) do nothing; end $$;
