import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const encoder=new TextEncoder();
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
function base64Url(input:Uint8Array|string){const bytes=typeof input==="string"?encoder.encode(input):input;let binary="";bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function pemToArrayBuffer(pem:string){const clean=pem.replace(/\\n/g,"\n").replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,"");const binary=atob(clean),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.buffer}
async function getAccessToken(projectId:string,clientEmail:string,privateKey:string){const now=Math.floor(Date.now()/1000),header=base64Url(JSON.stringify({alg:"RS256",typ:"JWT"})),claims=base64Url(JSON.stringify({iss:clientEmail,scope:"https://www.googleapis.com/auth/firebase.messaging",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600})),unsigned=`${header}.${claims}`,key=await crypto.subtle.importKey("pkcs8",pemToArrayBuffer(privateKey),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),signature=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,encoder.encode(unsigned)),jwt=`${unsigned}.${base64Url(new Uint8Array(signature))}`,response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:jwt})});if(!response.ok)throw new Error(`OAuth Firebase gagal (${response.status}).`);return (await response.json()).access_token as string}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});
 try{
  const body=await req.json(),target=String(body.target||"all"),athleteId=String(body.athleteId||""),coachId=String(body.coachId||""),title=String(body.title||"AQILAH Swimming Club"),message=String(body.body||body.message||"Ada informasi baru."),type=String(body.type||"push_notification"),referenceId=String(body.referenceId||body.eventId||""),defaultDeepLink=String(body.deepLink||body.page||"dashboard"),trainingCategories=Array.isArray(body.trainingCategories)?body.trainingCategories.map(String):[],ageGroups=Array.isArray(body.ageGroups)?body.ageGroups.map(String):[];
  const supabaseUrl=Deno.env.get("SUPABASE_URL"),serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),projectId=Deno.env.get("FIREBASE_PROJECT_ID"),clientEmail=Deno.env.get("FIREBASE_CLIENT_EMAIL"),privateKey=Deno.env.get("FIREBASE_PRIVATE_KEY");
  if(!supabaseUrl||!serviceRole||!projectId||!clientEmail||!privateKey)throw new Error("Secret Supabase/Firebase belum lengkap.");
  const supabase=createClient(supabaseUrl,serviceRole);
  let targetAthleteId=athleteId,targetCoachId=coachId;
  if(athleteId&&!uuid.test(athleteId)){const {data,error}=await supabase.from("asc_athletes").select("id").eq("legacy_id",athleteId).maybeSingle();if(error)throw error;targetAthleteId=String(data?.id||"")}
  if(coachId&&!uuid.test(coachId)){const {data,error}=await supabase.from("asc_coaches").select("id").eq("legacy_id",coachId).maybeSingle();if(error)throw error;targetCoachId=String(data?.id||"")}
  const {data,error}=await supabase.from("asc_push_devices").select("device_id,athlete_id,parent_id,coach_id,role,platform,fcm_token,last_seen").eq("inactive",false).is("deleted_at",null).not("fcm_token","is",null);if(error)throw error;
  const devices=Array.isArray(data)?data:[],athleteIds=[...new Set(devices.map(d=>d.athlete_id).filter(Boolean))],athleteMeta=new Map<string,{category:string;groups:string[]}>();
  if((trainingCategories.length||ageGroups.length)&&athleteIds.length){const {data:athletes,error:athleteError}=await supabase.from("asc_athletes").select("id,category,age_group,data").in("id",athleteIds).is("deleted_at",null);if(athleteError)throw athleteError;(athletes||[]).forEach(a=>athleteMeta.set(String(a.id),{category:String(a.category||a.data?.trainingCategory||""),groups:Array.isArray(a.data?.trainingGroups)?a.data.trainingGroups.map(String):[String(a.age_group||a.data?.ageGroup||"")].filter(Boolean)}))}
  const filtered=devices.filter(d=>{if(!d.fcm_token)return false;const parent=d.role==="parent",coach=d.role==="coach";if(target==="admin")return d.role==="admin";if(["parent","athlete_id"].includes(target))return parent&&(!athleteId||d.athlete_id===targetAthleteId||d.parent_id===targetAthleteId);if(["coach","coach_id"].includes(target))return coach&&(!coachId||d.coach_id===targetCoachId);if(target==="all_parents")return parent;if(target==="all_coaches")return coach;if(target==="all"&&!parent&&!coach)return false;if(target==="all"&&coach)return true;if(target==="all"&&parent){const meta=athleteMeta.get(String(d.athlete_id));return(!trainingCategories.length||trainingCategories.includes(meta?.category||""))&&(!ageGroups.length||ageGroups.some((g:string)=>meta?.groups.includes(g)))}return false});
  const unique=[...new Map(filtered.map(d=>[d.fcm_token,d])).values()];if(!unique.length)return json({ok:true,tokensFound:0,success:0,failed:0,invalidTokens:0});
  const accessToken=await getAccessToken(projectId,clientEmail,privateKey);let success=0,failed=0,invalidTokens=0;
  await Promise.all(unique.map(async device=>{const deepLink=device.role==="parent"?String(body.deepLinkParent||defaultDeepLink):device.role==="coach"?String(body.deepLinkCoach||defaultDeepLink):defaultDeepLink,response=await fetch(`https://fcm.googleapis.com/v1/projects/${projectId}/messages:send`,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({message:{token:device.fcm_token,notification:{title,body:message},data:{title,body:message,type,reference_id:referenceId,deep_link:deepLink},android:{priority:"high",notification:{channel_id:"aqilah_notifications",click_action:"OPEN_AQILAH_PUSH"}}}})});if(response.ok){success++;return}failed++;const detail=await response.text();if(/UNREGISTERED|registration-token-not-registered|INVALID_ARGUMENT/i.test(detail)){invalidTokens++;const now=new Date().toISOString();const {error:updateError}=await supabase.from("asc_push_devices").update({fcm_token:null,inactive:true,updated_at:now,last_seen:now}).eq("device_id",device.device_id);if(updateError)console.error("Token invalid gagal dinonaktifkan untuk device",device.device_id)}}));
  return json({ok:true,tokensFound:unique.length,success,failed,invalidTokens});
 }catch(error){console.error("send-push gagal:",error instanceof Error?error.message:String(error));return json({ok:false,error:error instanceof Error?error.message:String(error)},500)}
});
